apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: airflow
  labels:
    app: airflow
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: airflow
