apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: airflow
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.3.3
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: postgresql+psycopg2://airflow:airflow@postgres/airflow
        - name: AIRFLOW__CORE__FERNET_KEY
          value: your-fernet-key
        - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
          value: 'true'
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: 'false'
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags
        - name: airflow-logs
          mountPath: /opt/airflow/logs
        - name: airflow-plugins
          mountPath: /opt/airflow/plugins
      volumes:
      - name: airflow-dags
        emptyDir: {}
      - name: airflow-logs
        emptyDir: {}
      - name: airflow-plugins
        emptyDir: {}
